### ISSUE TITLE
Customize webcontrol Scrollbar and Disable any action on page

### ISSUE THREAD

**Issue by cpgtech** [awesomium/awesomium-pub#60]
Hello;

i would like to customize my WebControl in WPF application using c# (VS2013) and Awesomium library.

Objectives:
Disable any action on the web page(click , selection, mouseover ...)
And customize the scrollbar of webcontrol

Steps used:
First / To disable any action, i've used this code 

```
web_view.DocumentReady += (sender, e) =>
            {

                web_view.ExecuteJavascript("document.onselectstart=new Function ('return false;');");
                web_view.ExecuteJavascript("document.onclick=new Function ('return false;'); ");
                web_view.ExecuteJavascript("document.onmousedown=new Function ('return false;'); ");
                web_view.ExecuteJavascript("document.onmouseup=new Function ('return false;'); ");
                web_view.ExecuteJavascript("document.onmouseover=new Function ('return false;'); ");
            };
```

but only a few clicks and selection are disabled.

Second / so i set IsEnabled= FALSE 
it seems to work but the scroll bar does not scroll.

Third / i've embeded webcontronl in scrollviewer and customize it

  `<ScrollViewer Margin="0,0,0,0" VerticalScrollBarVisibility="Visible" HorizontalScrollBarVisibility="Visible" >
  <awe:WebControl  IsEnabled="False"  x:Name="web_view" Margin="0"   Source="http://www.yahoo.fr"   ShowContextMenu="web_view_ShowContextMenu" />
</ScrollViewer >`

Problem:
The web page disappears when I reduce my window, the Awesomium logo  appears . or web page does not appear when I want to display the horizontal scroll bar..

Question: 
Is there a better way to disable all the action on webpage while keeping the page scrolling? 
How can I customize the scrollbar of webcontrol in WPF?

Thanks

**Comment by pixelport** [comment]
You cant customize the scrollbars in WPF because they are rendered in the chromium engine. You could try a few things:
- check the webControl PreviewMouseMove event and set e.isHandled to true if Mouse Position is not on the scrollbar
- check all your javascript functions which element is clicked and stop the event if the click is not on a scrollbar. Right now you are preventing all

You should remove the scrollViewer. The scroll bars shown are not from the scrollViewer.
I would try option 1 should be easiest. I hope I could help.

**Comment by Perikles** [comment]
This question is discussed **[here](http://answers.awesomium.com/questions/5330/)**.
